# Generated by Django 4.1.5 on 2023-03-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='mobile',
        ),
    ]
